#display a diamond pattern
print("                                    *                                             ")
print("                                  *****                                           ")
print("                                *********                                         ")
print("                               ***********                                        ")
print("                              *************                                       ")
print("                             ***************                                      ")
print("                              *************                                       ")
print("                               ***********                                        ")
print("                                *********                                         ")
print("                                 *******                                          ")
print("                                  *****                                           ")
print("                                   ***                                            ") 
print("                                    *                                             ")

