#Write a program to display a big T pattern
print("=============================================================")
print("=============================================================")
print("=============================================================")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")
print("                            ||                               ")

